fix travis file

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,7 +4,15 @@ python:
 
 env:
   global:
-    STATUS=mock
+#    - >
+#      STATUS=$'curl -so/dev/null --user "$MBED_BOT" --request POST
+#      https://api.github.com/repos/$TRAVIS_REPO_SLUG/statuses/${TRAVIS_PULL_REQUEST_SHA:-$TRAVIS_COMMIT}
+#      --data @- << DATA\n{
+#      "state": "$0",
+#      "description": "$1",
+#      "context": "travis-ci/$NAME",
+#      "target_url": "https://travis-ci.org/$TRAVIS_REPO_SLUG/jobs/$TRAVIS_JOB_ID"
+#      }\nDATA'
 
 cache:
   pip: true
@@ -13,7 +21,7 @@ cache:
     - $HOME/gcc-arm-none-eabi-6-2017-q2-update
 
 before_install:
-  - bash -c "$STATUS" pending "Local $NAME testing is in progress"
+#  - bash -c "$STATUS" pending "Local $NAME testing is in progress"
   # Make sure pipefail
   - set -o pipefail
   # Setup apt to cache
@@ -26,10 +34,10 @@ before_install:
   - travis_retry $(! sudo apt-get update 2>&1 |grep Failed)
 
 after_success:
-  - bash -c "$STATUS" success "Local $NAME testing has passed"
+#  - bash -c "$STATUS" success "Local $NAME testing has passed"
 
 after_failure:
-  - bash -c "$STATUS" failure "Local $NAME testing has failed"
+#  - bash -c "$STATUS" failure "Local $NAME testing has failed"
 
 matrix:
   include:
@@ -84,7 +92,7 @@ matrix:
         # Coverage for tools
         - coveralls
         # Report success since we have overridden default behaviour
-        - bash -c "$STATUS" success "Local $NAME testing has passed"
+#        - bash -c "$STATUS" success "Local $NAME testing has passed"
 
     - env:
         - NAME=events
@@ -112,22 +120,22 @@ matrix:
         - make -C $EVENTS/equeue prof | tee prof
       after_success:
         # update status if we succeeded, compare with master if possible
-        - |
-          CURR=$(grep -o '[0-9]\+ cycles' prof | awk '{sum += $1} END {print sum}')
-          PREV=$(curl https://api.github.com/repos/$TRAVIS_REPO_SLUG/status/master \
-              | jq -re "select(.sha != \"$TRAVIS_COMMIT\")
-                  | .statuses[] | select(.context == \"travis-ci/$NAME\").description
-                  | capture(\"runtime is (?<runtime>[0-9]+)\").runtime" \
-              || echo 0)
-
-          STATUSM="Passed, runtime is ${CURR} cycles"
-          if [ "$PREV" -ne 0 ]
-          then
-              STATUSM="$STATUSM ($(python -c "print '%+d' % ($CURR-$PREV)") cycles)"
-          fi
+#        - |
+#          CURR=$(grep -o '[0-9]\+ cycles' prof | awk '{sum += $1} END {print sum}')
+#          PREV=$(curl https://api.github.com/repos/$TRAVIS_REPO_SLUG/status/master \
+#              | jq -re "select(.sha != \"$TRAVIS_COMMIT\")
+#                  | .statuses[] | select(.context == \"travis-ci/$NAME\").description
+#                  | capture(\"runtime is (?<runtime>[0-9]+)\").runtime" \
+#              || echo 0)
+#
+#          STATUSM="Passed, runtime is ${CURR} cycles"
+#          if [ "$PREV" -ne 0 ]
+#          then
+#              STATUSM="$STATUSM ($(python -c "print '%+d' % ($CURR-$PREV)") cycles)"
+#          fi
         # Coverage for events
         - coveralls --exclude tests --gcov-options '\-lp'
-        - bash -c "$STATUS" success "$STATUSM"
+#        - bash -c "$STATUS" success "$STATUSM"
 
     - env:
         - NAME=littlefs
@@ -187,16 +195,16 @@ matrix:
       after_success:
         # update status if we succeeded, compare with master if possible
         - |
-          CURR=$(tail -n1 sizes | awk '{print $1}')
-          PREV=$(curl https://api.github.com/repos/$TRAVIS_REPO_SLUG/status/master \
-              | jq -re "select(.sha != \"$TRAVIS_COMMIT\")
-                  | .statuses[] | select(.context == \"travis-ci/$NAME\").description
-                  | capture(\"code size is (?<size>[0-9]+)\").size" \
-              || echo 0)
+#          CURR=$(tail -n1 sizes | awk '{print $1}')
+#          PREV=$(curl https://api.github.com/repos/$TRAVIS_REPO_SLUG/status/master \
+#              | jq -re "select(.sha != \"$TRAVIS_COMMIT\")
+#                  | .statuses[] | select(.context == \"travis-ci/$NAME\").description
+#                  | capture(\"code size is (?<size>[0-9]+)\").size" \
+#              || echo 0)
 
-          STATUSM="Passed, code size is ${CURR}B"
-          if [ "$PREV" -ne 0 ]
-          then
-              STATUSM="$STATUSM ($(python -c "print '%+.2f' % (100*($CURR-$PREV)/$PREV.0)")%)"
-          fi
-        - bash -c "$STATUS" success "$STATUSM"
+#          STATUSM="Passed, code size is ${CURR}B"
+#          if [ "$PREV" -ne 0 ]
+#          then
+#              STATUSM="$STATUSM ($(python -c "print '%+.2f' % (100*($CURR-$PREV)/$PREV.0)")%)"
+#          fi
+#        - bash -c "$STATUS" success "$STATUSM"
